language: node_js
node_js:
 - "lts/*"

cache:
  npm: false

before_install:
  # NPM Login - commercial
  # - npm config set @sencha:registry https://npm.sencha.com/
  # - npm config set //npm.sencha.com/:_authToken=$SENCHA_NPM_TOKEN_VERDACCIO
  # NPM Login - early-adopter
  - npm config set @sencha:registry https://sencha.myget.org/F/early-adopter/npm/
  - npm config set //sencha.myget.org/F/early-adopter/npm/:_authToken=$SENCHA_NPM_TOKEN_EARLYADOPTER
  # For early adopter clean the cache 
  # Remove all package-lock.json files for early adopter. 
  #- npm cache clean --force
  #- npm cache verify

install: 
  - npm install
  - ls
  - pwd
  - cd ./client
  - pwd
  - npm install

script:
  - pwd
  - npm run build
  
before_deploy:
  - pwd
  - cd ..
  - pwd
  # Copy the web app into the server static html directory
  - cp -R ./client/build/production/ModernApp/* ./server/html
  # Get rid of the files that aren't needed in the deployment
  - rm -rf ./client
  # Add the server libraries
  - git add -f node_modules/
  - git add -A

deploy:
  - provider: elasticbeanstalk
    edge: true
    skip_cleanup: true
    access_key_id:
      secure: "jmW7MzPR5yur4vYsbKV1K4CrVmgs2b2QkphF4yDLDpNaYkLtvqs47HKJ0+WLc+raVDRt+0ZYxenhQMGeR7QNFl3JynL/ZxgzVH2S2BHReKX0QoeqcEbL9hSuO+iMgyOUSV8yvcJ/w6TMZrHR0WDpalVoQ9/CKPv2a4WZ5XN/itcgeatr7yBH5w2ehvNS0rEkFLRCoCZkVb4u7TcYbhM8SkXzNM69VAPxy/0exoLD+TUd7m9nET8pNHlqQmrjjs8koQvT8CDf8CLiRmEUfgMiPbIgdtm/Vuu2C/0jh4x8jpPMSvjDhAWtCDKMYalHNfCdmJygHqgP/d6VbuRp3gxa1CQEJMaKzFU3BSLP/prkg607jBqsydAHg85FNaQI66SxIbSGemveirQSjnR2UixWRYyPYnuBLhPlEazSM8FLKnME3IY3I2ir8Y0CTRfZ3a0LRfaczht7ciKXYGMHT5GdlxXHmn2oprQ6oDLJ20IfGmnz8Puufa16zhIz3xE/OAp230lRdECzeedeX3h8FIjme39GwzdvlNmOc4J0dTkp9HkWOrnjs9n+1bxGLFB6Wn6JQ4CRvvWImchtZA8MpNqEvFOslIDuno3wiWV+D1hjSQrR9CrKmYNZDQCZ8WPgiDj0CZN4GAEfHs9wm323o7N9gZ4bEfKMt9TYMSva9F2mxxU=" 
    secret_access_key:
      secure: "Hrn51O91Pd6SCCgygXnTfjcMM8Vruk2VvPC761cF6zEH4zlqLxt0vbQabZag9LJOrv4sTnPHc1gb5S1JLjrjolJn1M9YaH9Nqt5IGhMeRmv42OaNK2MMCPFdZYA8it7StDKIS7W3Dr+H852GI+ejUaf4o941z5sdrxOSIp2H+2QWvSI6gpGeJiXmTs+i5LjYVd/n7SBXCZ/bmKOTox/S1ORa8GAlrCJ9eieJDhrLk8rTPgq5Qkl268F5WKaPmCN5142eB5+FsnpF/cg9xvO+V7NEmQro7CHWUaMUHzhO5L+rpesvx2USQ4GjpywqpzqFme1V0TZsPo9/KAiehm58Mt1+98uDlpkLaxcdd3LjR3cQbq8UjkEahEZqIQIn7eVogqmuZoy/EIX0CV5f5sUfGnZpmpg7l6fREcTEEzXXynlbKC2EEmTsDxEmuI+ApuaaoCUEh1nUVSjnMG63D8jPAW4ahkfcPEU4leNxXrC0KQ5Xumah9ZSK4ZOZsc1HAiDYUwWji++Msy6ZEZuuMgcTTo2Agdl55Sz4KlKQpKqps+V0Tah37vWqPqpkf8VYvF2yzx2DH0Ee8UPfsoc1Yt+RxfK1vyfm0eK9qHgYHZTeZtOUJMpksN7ynpJE+DIatZviJm+JJkmaDIfYpUd4mwSx0hDDb6xcVd9/N8eqk9Y0/Y8=" 
    region: "us-east-1"
    app: "sandbox-extjs-travis-aws"
    env: "sandbox-staging"
    bucket_name: "sencha-deploy-from-travis-tmp"


# Notes:
# https://travis-ci.com/github/sencha/sandbox-extjs-travis-aws/settings - contains private export variables

# Run Travis CLI in this repo
# gem install travis

# Delete Travis Cache
# travis cache --com
# travis cache --com --delete

# Encrypt Secure Variables
# gem install travis
# travis login --pro --github-token replace_with_github_personal_token
# cd to/this/repo
# travis encrypt xxx_key_id
# travis encrypt xxx_access_key