branch-defaults:
  master:
    environment: sandbox-staging
    group_suffix: null
global:
  application_name: sandbox-extjs-travis-aws
  branch: null
  default_ec2_keyname: Sencha-AWS
  default_platform: Multi-container Docker 18.09.9-ce (Generic)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
